env: "grid_mpe"

env_args:
  map_name: grid_mpe      # 名字,会自动生成
  n_agents: 2             # 有几个智能体
  field_size: [6,6]       # 地图大小
  sight: 5                 # sight大小
  episode_limit: 50       # 
  reach_range: 2
  default_task: True
  task_id: 3
  # seed: 7

test_greedy: True
test_nepisode: 32
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 4050000