# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "marine_battle"
# define train tasks and test tasks
train_tasks: ["5m", "5m_vs_6m", "8m_vs_9m", "10m_vs_11m"]
test_task: "10m_vs_12m"
test_tasks: ["3m", "3m_vs_4m", "4m", "4m_vs_5m", "5m", "5m_vs_6m", "5m_vs_7m", "6m", "6m_vs_7m", "7m", "7m_vs_8m", "8m", "8m_vs_9m", "9m", "9m_vs_10m", "10m", "10m_vs_11m", "10m_vs_12m"]
